# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataBaseGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1107, 845)
        MainWindow.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 70, 1081, 721))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(930, 30, 151, 25))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(880, 30, 41, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(880, 0, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(960, 0, 121, 21))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 231, 51))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1107, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menu_2)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menu_2)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.action_10 = QtWidgets.QAction(MainWindow)
        self.action_10.setObjectName("action_10")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_11 = QtWidgets.QAction(MainWindow)
        self.action_11.setObjectName("action_11")
        self.action_12 = QtWidgets.QAction(MainWindow)
        self.action_12.setObjectName("action_12")
        self.action_13 = QtWidgets.QAction(MainWindow)
        self.action_13.setObjectName("action_13")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.actionPrimary_key = QtWidgets.QAction(MainWindow)
        self.actionPrimary_key.setObjectName("actionPrimary_key")
        self.actionPrimary_key_2 = QtWidgets.QAction(MainWindow)
        self.actionPrimary_key_2.setObjectName("actionPrimary_key_2")
        self.actionAttribute = QtWidgets.QAction(MainWindow)
        self.actionAttribute.setObjectName("actionAttribute")
        self.actionAttribute_2 = QtWidgets.QAction(MainWindow)
        self.actionAttribute_2.setObjectName("actionAttribute_2")
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menu.addAction(self.action_4)
        self.menu_3.addAction(self.action_5)
        self.menu_3.addAction(self.action_10)
        self.menu_3.addAction(self.actionAttribute)
        self.menu_4.addAction(self.action_6)
        self.menu_4.addAction(self.action_11)
        self.menu_4.addAction(self.actionAttribute_2)
        self.menu_2.addAction(self.action_9)
        self.menu_2.addAction(self.menu_3.menuAction())
        self.menu_2.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DataBase Managemen System (DBMS)"))
        self.label.setText(_translate("MainWindow", "TABLE:"))
        self.label_2.setText(_translate("MainWindow", "DATA BASE:"))
        self.pushButton.setText(_translate("MainWindow", "Change cortege"))
        self.menu.setTitle(_translate("MainWindow", "File"))
        self.menu_2.setTitle(_translate("MainWindow", "Data Base"))
        self.menu_3.setTitle(_translate("MainWindow", "Add"))
        self.menu_4.setTitle(_translate("MainWindow", "Delete"))
        self.action.setText(_translate("MainWindow", "Open"))
        self.action_2.setText(_translate("MainWindow", "Save"))
        self.action_3.setText(_translate("MainWindow", "Save as"))
        self.action_4.setText(_translate("MainWindow", "Exit"))
        self.action_5.setText(_translate("MainWindow", "Table"))
        self.action_7.setText(_translate("MainWindow", "Атрибут"))
        self.action_9.setText(_translate("MainWindow", "Connect"))
        self.action_10.setText(_translate("MainWindow", "Cortege"))
        self.action_6.setText(_translate("MainWindow", "Table"))
        self.action_11.setText(_translate("MainWindow", "Cortege"))
        self.action_12.setText(_translate("MainWindow", "Атрибут"))
        self.action_13.setText(_translate("MainWindow", "Список таблиц"))
        self.action_8.setText(_translate("MainWindow", "Скопировать"))
        self.actionPrimary_key.setText(_translate("MainWindow", "Primary key"))
        self.actionPrimary_key_2.setText(_translate("MainWindow", "Primary key"))
        self.actionAttribute.setText(_translate("MainWindow", "Attribute"))
        self.actionAttribute_2.setText(_translate("MainWindow", "Attribute"))

